Repository GDG-24-25-KAKAOBANK-Android/GDG-Team1, pull requests merged in 2024-11, with the labels that each got.

#2 [SETTING] 폴더 구성 및 폰트 시스템 구성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/kakaobank/domain/entity/ExampleEntity.kt
  app/src/main/java/com/gdg/kakaobank/presentation/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/gdg/kakaobank/presentation/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/gdg/kakaobank/presentation/main/screen/MainActivity.kt
  app/src/main/java/com/gdg/kakaobank/presentation/navigator/KakaoNavHost.kt
  app/src/main/java/com/gdg/kakaobank/ui/theme/Type.kt
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 서연🐱, WEEK01, setting

#4 [SETTING] 컬러 시스템 추가
  app/src/main/java/com/gdg/kakaobank/ui/theme/Color.kt
  app/src/main/java/com/gdg/kakaobank/ui/theme/Theme.kt
Labels: WEEK01, setting, 현진🐤

#8 [UI] 스플래시 구현
  app/src/main/java/com/gdg/kakaobank/presentation/auth/screen/SplashScreen.kt
  app/src/main/res/drawable/symbol_kakaobank.png
Labels: WEEK01, ui, 현진🐤

#10 [MOD] 글씨 색 변환 구현
  app/src/main/java/com/gdg/kakaobank/presentation/main/screen/MainScreen.kt
  app/src/main/java/com/gdg/kakaobank/ui/component/BottomNavigationItem.kt
Labels: 서연🐱, WEEK01, ui, mod

#12 [UI] 혜택 페이지 구현
  app/src/main/java/com/gdg/kakaobank/app/di/ExampleEntity.kt
  app/src/main/java/com/gdg/kakaobank/data/datasource/ExampleDatasource.kt
  app/src/main/java/com/gdg/kakaobank/data/datasourceimpl/ExampleDatasourceimpl.kt
  app/src/main/java/com/gdg/kakaobank/data/dto/ExampleDto.kt
  app/src/main/java/com/gdg/kakaobank/data/repositoryimpl/ExampleRepositoryimpl.kt
  app/src/main/java/com/gdg/kakaobank/data/service/ExampleApiService.java
  app/src/main/java/com/gdg/kakaobank/domain/entity/ExampleEntity.kt
  app/src/main/java/com/gdg/kakaobank/domain/repository/ExampleRepository.kt
  app/src/main/java/com/gdg/kakaobank/presentation/benefit/screen/BenefitLikeItem.kt
  app/src/main/java/com/gdg/kakaobank/presentation/benefit/screen/BenefitScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/benefit/screen/BenefitSendItem.kt
  app/src/main/res/drawable/ic_benefit_selected_heart.xml
  app/src/main/res/drawable/ic_benefit_send.xml
  app/src/main/res/drawable/ic_benefit_unselected_heart.xml
  app/src/main/res/values/strings.xml
Labels: 서연🐱, WEEK02, ui

#15 [UI] 전체 페이지 구현
  app/src/main/java/com/gdg/kakaobank/presentation/other/screen/OtherLogoutDialog.kt
  app/src/main/java/com/gdg/kakaobank/presentation/other/screen/OtherScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/other/screen/OtherWithdrawDialog.kt
  app/src/main/java/com/gdg/kakaobank/ui/theme/Type.kt
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/values/strings.xml
Labels: WEEK02, ui, 현진🐤

#18 [MOD] 홈 네비게이션 수정, warning 제거
  app/src/main/java/com/gdg/kakaobank/presentation/home/screen/HomeScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/other/screen/OtherLogoutDialog.kt
  app/src/main/java/com/gdg/kakaobank/presentation/other/screen/OtherScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/other/screen/OtherWithdrawDialog.kt
Labels: 서연🐱, WEEK02, 현진🐤, mod

#20 [UI] 탭페이저, 저축, 카드, 투자, 대출 페이지 구현
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/GoodsScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/GoodsTabPager.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsAccount/GoodsAccountScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsCard/GoodsCardEntity.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsCard/GoodsCardItem.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsCard/GoodsCardScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsCard/GoodsCardViewModel.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsInvest/GoodsInvestScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsLoan/GoodsLoanScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsRecommend/GoodsRecommendScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsSaving/GoodsSavingEntity.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsSaving/GoodsSavingItem.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsSaving/GoodsSavingScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsSaving/GoodsSavingViewModel.kt
  app/src/main/java/com/gdg/kakaobank/presentation/other/screen/OtherScreen.kt
  app/src/main/java/com/gdg/kakaobank/ui/component/GoodsBox.kt
  app/src/main/res/values/strings.xml
Labels: 서연🐱, ui, week03

#22 [UI] 상품 - 추천 화면 구현
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsRecommend/GoodsRecommendEntity.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsRecommend/GoodsRecommendItem.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsRecommend/GoodsRecommendScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsRecommend/GoodsRecommendViewModel.kt
  app/src/main/res/drawable/ic_goods_bank.xml
  app/src/main/res/drawable/ic_goods_bankbook.xml
  app/src/main/res/drawable/ic_goods_handheart.xml
  app/src/main/res/drawable/ic_goods_loan.xml
  app/src/main/res/drawable/ic_goods_money.xml
  app/src/main/res/drawable/ic_goods_truck.xml
Labels: ui, 현진🐤, week03
