Repository GDG-24-25-KAKAOBANK-Android/GDG-Team1, pull requests merged in 2024-12, with the labels that each got.

#24 [UI] 상품 - 통장 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/kakaobank/api/ApiFactory.kt
  app/src/main/java/com/gdg/kakaobank/api/ResposeUserDto.kt
  app/src/main/java/com/gdg/kakaobank/api/UserService.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsAccount/GoodsAccountScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsAccount/GoodsAccountViewModel.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsRecommend/GoodsRecommendItem.kt
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsRecommend/GoodsRecommendScreen.kt
Labels: ui, 현진🐤, week03

#26 [UI] 이체 - 이체 화면 구현 및 다음 & 닫기 기능 구현
  app/src/main/java/com/gdg/kakaobank/presentation/goods/screen/goodsRecommend/GoodsRecommendScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/gdg/kakaobank/presentation/home/navigation/HomeNavigator.kt
  app/src/main/java/com/gdg/kakaobank/presentation/home/screen/HomeScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/navigator/KakaoNavHost.kt
  app/src/main/java/com/gdg/kakaobank/presentation/transfer/screen/SendScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/transfer/screen/TransferScreen.kt
  app/src/main/java/com/gdg/kakaobank/ui/component/NextBox.kt
  app/src/main/res/drawable/ic_transfer_line.xml
  app/src/main/res/drawable/ic_transfer_search.xml
  app/src/main/res/values/strings.xml
Labels: ui, 현진🐤, WEEK04

#28 [UI] 이체 텍스트 필드, 뒤로 가기 바텀시트 구현
  app/src/main/java/com/gdg/kakaobank/presentation/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/gdg/kakaobank/presentation/home/navigation/HomeNavigator.kt
  app/src/main/java/com/gdg/kakaobank/presentation/home/screen/SendScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/home/screen/TransferScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/main/screen/MainActivity.kt
  app/src/main/java/com/gdg/kakaobank/presentation/transfer/screen/SendScreen.kt
  app/src/main/java/com/gdg/kakaobank/ui/component/KakaoBottomSheet.kt
  app/src/main/java/com/gdg/kakaobank/ui/component/NextBox.kt
  app/src/main/java/com/gdg/kakaobank/ui/theme/Color.kt
Labels: 서연🐱, ui, WEEK04

#30 [UI] 이체 - 송금 페이지, 이체 완료 페이지 구현
  app/src/main/java/com/gdg/kakaobank/presentation/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/gdg/kakaobank/presentation/home/navigation/HomeNavigator.kt
  app/src/main/java/com/gdg/kakaobank/presentation/home/screen/SendScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/home/screen/TransferEnd.kt
  app/src/main/res/drawable/ic_transferend_checked.xml
  app/src/main/res/values/strings.xml
Labels: ui, 현진🐤, WEEK04

#32 [UI] Splash 이미지 svg로 수정
  app/src/main/java/com/gdg/kakaobank/presentation/auth/screen/SplashScreen.kt
  app/src/main/res/drawable/ic_splash_logo.xml
  app/src/main/res/drawable/symbol_kakaobank.png
Labels: 현진🐤, mod, WEEK04
